package ma.sofisoft.cam2020ws.entity;
// Generated 15 nov. 2019 10:03:37 by Hibernate Tools 4.3.5.Final

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * CfgUtilisateurId generated by hbm2java
 */
@Embeddable
public class CfgUtilisateurId implements java.io.Serializable {

	private long numUtilisateur;
	private long numMagasin;

	public CfgUtilisateurId() {
	}

	public CfgUtilisateurId(long numUtilisateur, long numMagasin) {
		this.numUtilisateur = numUtilisateur;
		this.numMagasin = numMagasin;
	}

	@Column(name = "NUM_UTILISATEUR", nullable = false, precision = 10, scale = 0)
	public long getNumUtilisateur() {
		return this.numUtilisateur;
	}

	public void setNumUtilisateur(long numUtilisateur) {
		this.numUtilisateur = numUtilisateur;
	}

	@Column(name = "NUM_MAGASIN", nullable = false, precision = 10, scale = 0)
	public long getNumMagasin() {
		return this.numMagasin;
	}

	public void setNumMagasin(long numMagasin) {
		this.numMagasin = numMagasin;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof CfgUtilisateurId))
			return false;
		CfgUtilisateurId castOther = (CfgUtilisateurId) other;

		return (this.getNumUtilisateur() == castOther.getNumUtilisateur())
				&& (this.getNumMagasin() == castOther.getNumMagasin());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (int) this.getNumUtilisateur();
		result = 37 * result + (int) this.getNumMagasin();
		return result;
	}

}
