package ma.sofisoft.cam2020ws.entity;
// Generated 15 nov. 2019 10:03:37 by Hibernate Tools 4.3.5.Final

import java.math.BigDecimal;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.UniqueConstraint;

/**
 * DspMagasin generated by hbm2java
 */
@Entity
@Table(name = "DSP_MAGASIN", uniqueConstraints = @UniqueConstraint(columnNames = "CODE_MAGASIN"))
public class DspMagasin implements java.io.Serializable {

	private long numMagasin;
	private Integer numSociete;
	private Byte codeCategorie;
	private long numDevise;
	private long cptNumDevise;
	private Long numPaiement;
	private String codeMagasin;
	private String adresse;
	private String ville;
	private String pays;
	private String telephone;
	private String fax;
	private String EMail;
	private String webPage;
	private Integer bloque;
	private String gerant;
	private Integer status;
	private int informatique;
	private Integer nbrLivraison;
	private BigDecimal caAnneePrec;
	private BigDecimal caAnnee;
	private BigDecimal caMois;
	private BigDecimal encours;
	private Integer gererStock;
	private String nomMagasin;
	private String observations;
	private BigDecimal pourcentage;
	private Integer priorite;
	private int typeFacturation;
	private BigDecimal superficie;
	private Long numCompte;
	private Long numRepresentant;
	private String osSerialNumber;
	private String diskSerialNumber;
	private String softCode;
	private String region;
	private String localite;
	private String mobile;
	private String prefixeCodeCmd;
	private String compteurCodeCmd;
	private String prefixeCodeLiv;
	private String compteurCodeLiv;
	private String prefixeCodeFac;
	private String compteurCodeFac;
	private String prefixeCodeReg;
	private String compteurCodeReg;
	private String prefixeCodeRet;
	private String compteurCodeRet;
	private String prefixeCodeAvr;
	private String compteurCodeAvr;
	private String prefixeCodeEch;
	private String compteurCodeEch;
	private int venteHt;
	private int prixVntCatMag;
	private int regMultiDevise;
	private int renduMultiDevise;
	private Integer numRegion;
	private Integer numLocalite;
	private Integer numVille;
	private Date dateOuverture;
	private Long numCompteAuxiliaire;
	private Integer updateBasePos;
	private Integer updatePrgPos;
	private String photoMagasin;
	private Date dateFermeture;
	private BigDecimal coordLongitude;
	private BigDecimal coordLatitude;
	private Integer entrepot;
	private Date dateSurfaceEgale;
	private Integer gereCarManuel;
	private String ice;

	public DspMagasin() {
	}
	
	public DspMagasin(long numMagasin, String codeMagasin, String nomMagasin) {
		super();
		this.numMagasin = numMagasin;
		this.codeMagasin = codeMagasin;
		this.nomMagasin = nomMagasin;
	}	

	public DspMagasin(long numMagasin, long numDevise, long cptNumDevise, String codeMagasin, int informatique,
			int typeFacturation, int venteHt, int prixVntCatMag, int regMultiDevise, int renduMultiDevise) {
		this.numMagasin = numMagasin;
		this.numDevise = numDevise;
		this.cptNumDevise = cptNumDevise;
		this.codeMagasin = codeMagasin;
		this.informatique = informatique;
		this.typeFacturation = typeFacturation;
		this.venteHt = venteHt;
		this.prixVntCatMag = prixVntCatMag;
		this.regMultiDevise = regMultiDevise;
		this.renduMultiDevise = renduMultiDevise;
	}

	public DspMagasin(long numMagasin, Integer numSociete, Byte codeCategorie, long numDevise, long cptNumDevise,
			Long numPaiement, String codeMagasin, String adresse, String ville, String pays, String telephone,
			String fax, String EMail, String webPage, Integer bloque, String gerant, Integer status, int informatique,
			Integer nbrLivraison, BigDecimal caAnneePrec, BigDecimal caAnnee, BigDecimal caMois, BigDecimal encours,
			Integer gererStock, String nomMagasin, String observations, BigDecimal pourcentage, Integer priorite,
			int typeFacturation, BigDecimal superficie, Long numCompte, Long numRepresentant,
			String osSerialNumber, String diskSerialNumber, String softCode, String region,
			String localite, String mobile, String prefixeCodeCmd, String compteurCodeCmd, String prefixeCodeLiv,
			String compteurCodeLiv, String prefixeCodeFac, String compteurCodeFac, String prefixeCodeReg,
			String compteurCodeReg, String prefixeCodeRet, String compteurCodeRet, String prefixeCodeAvr,
			String compteurCodeAvr, String prefixeCodeEch, String compteurCodeEch, int venteHt, int prixVntCatMag,
			int regMultiDevise, int renduMultiDevise, Integer numRegion, Integer numLocalite, Integer numVille,
			Date dateOuverture, Long numCompteAuxiliaire, Integer updateBasePos, Integer updatePrgPos,
			String photoMagasin, Date dateFermeture, BigDecimal coordLongitude, BigDecimal coordLatitude,
			Integer entrepot, Date dateSurfaceEgale, Integer gereCarManuel, String ice) {
		this.numMagasin = numMagasin;
		this.numSociete = numSociete;
		this.codeCategorie = codeCategorie;
		this.numDevise = numDevise;
		this.cptNumDevise = cptNumDevise;
		this.numPaiement = numPaiement;
		this.codeMagasin = codeMagasin;
		this.adresse = adresse;
		this.ville = ville;
		this.pays = pays;
		this.telephone = telephone;
		this.fax = fax;
		this.EMail = EMail;
		this.webPage = webPage;
		this.bloque = bloque;
		this.gerant = gerant;
		this.status = status;
		this.informatique = informatique;
		this.nbrLivraison = nbrLivraison;
		this.caAnneePrec = caAnneePrec;
		this.caAnnee = caAnnee;
		this.caMois = caMois;
		this.encours = encours;
		this.gererStock = gererStock;
		this.nomMagasin = nomMagasin;
		this.observations = observations;
		this.pourcentage = pourcentage;
		this.priorite = priorite;
		this.typeFacturation = typeFacturation;
		this.superficie = superficie;
		this.numCompte = numCompte;
		this.numRepresentant = numRepresentant;
		this.osSerialNumber = osSerialNumber;
		this.diskSerialNumber = diskSerialNumber;
		this.softCode = softCode;
		this.region = region;
		this.localite = localite;
		this.mobile = mobile;
		this.prefixeCodeCmd = prefixeCodeCmd;
		this.compteurCodeCmd = compteurCodeCmd;
		this.prefixeCodeLiv = prefixeCodeLiv;
		this.compteurCodeLiv = compteurCodeLiv;
		this.prefixeCodeFac = prefixeCodeFac;
		this.compteurCodeFac = compteurCodeFac;
		this.prefixeCodeReg = prefixeCodeReg;
		this.compteurCodeReg = compteurCodeReg;
		this.prefixeCodeRet = prefixeCodeRet;
		this.compteurCodeRet = compteurCodeRet;
		this.prefixeCodeAvr = prefixeCodeAvr;
		this.compteurCodeAvr = compteurCodeAvr;
		this.prefixeCodeEch = prefixeCodeEch;
		this.compteurCodeEch = compteurCodeEch;
		this.venteHt = venteHt;
		this.prixVntCatMag = prixVntCatMag;
		this.regMultiDevise = regMultiDevise;
		this.renduMultiDevise = renduMultiDevise;
		this.numRegion = numRegion;
		this.numLocalite = numLocalite;
		this.numVille = numVille;
		this.dateOuverture = dateOuverture;
		this.numCompteAuxiliaire = numCompteAuxiliaire;
		this.updateBasePos = updateBasePos;
		this.updatePrgPos = updatePrgPos;
		this.photoMagasin = photoMagasin;
		this.dateFermeture = dateFermeture;
		this.coordLongitude = coordLongitude;
		this.coordLatitude = coordLatitude;
		this.entrepot = entrepot;
		this.dateSurfaceEgale = dateSurfaceEgale;
		this.gereCarManuel = gereCarManuel;
		this.ice = ice;
	}

	@Id

	@Column(name = "NUM_MAGASIN", unique = true, nullable = false, precision = 10, scale = 0)
	public long getNumMagasin() {
		return this.numMagasin;
	}

	public void setNumMagasin(long numMagasin) {
		this.numMagasin = numMagasin;
	}

	@Column(name = "NUM_SOCIETE")
	public Integer getNumSociete() {
		return this.numSociete;
	}

	public void setNumSociete(Integer numSociete) {
		this.numSociete = numSociete;
	}

	@Column(name = "CODE_CATEGORIE", precision = 2, scale = 0)
	public Byte getCodeCategorie() {
		return this.codeCategorie;
	}

	public void setCodeCategorie(Byte codeCategorie) {
		this.codeCategorie = codeCategorie;
	}

	@Column(name = "NUM_DEVISE", nullable = false, precision = 10, scale = 0)
	public long getNumDevise() {
		return this.numDevise;
	}

	public void setNumDevise(long numDevise) {
		this.numDevise = numDevise;
	}

	@Column(name = "CPT_NUM_DEVISE", nullable = false, precision = 10, scale = 0)
	public long getCptNumDevise() {
		return this.cptNumDevise;
	}

	public void setCptNumDevise(long cptNumDevise) {
		this.cptNumDevise = cptNumDevise;
	}

	@Column(name = "NUM_PAIEMENT", precision = 10, scale = 0)
	public Long getNumPaiement() {
		return this.numPaiement;
	}

	public void setNumPaiement(Long numPaiement) {
		this.numPaiement = numPaiement;
	}

	@Column(name = "CODE_MAGASIN", unique = true, nullable = false, length = 10)
	public String getCodeMagasin() {
		return this.codeMagasin;
	}

	public void setCodeMagasin(String codeMagasin) {
		this.codeMagasin = codeMagasin;
	}

	@Column(name = "ADRESSE", length = 50)
	public String getAdresse() {
		return this.adresse;
	}

	public void setAdresse(String adresse) {
		this.adresse = adresse;
	}

	@Column(name = "VILLE", length = 30)
	public String getVille() {
		return this.ville;
	}

	public void setVille(String ville) {
		this.ville = ville;
	}

	@Column(name = "PAYS", length = 30)
	public String getPays() {
		return this.pays;
	}

	public void setPays(String pays) {
		this.pays = pays;
	}

	@Column(name = "TELEPHONE", length = 30)
	public String getTelephone() {
		return this.telephone;
	}

	public void setTelephone(String telephone) {
		this.telephone = telephone;
	}

	@Column(name = "FAX", length = 30)
	public String getFax() {
		return this.fax;
	}

	public void setFax(String fax) {
		this.fax = fax;
	}

	@Column(name = "E_MAIL", length = 30)
	public String getEMail() {
		return this.EMail;
	}

	public void setEMail(String EMail) {
		this.EMail = EMail;
	}

	@Column(name = "WEB_PAGE", length = 50)
	public String getWebPage() {
		return this.webPage;
	}

	public void setWebPage(String webPage) {
		this.webPage = webPage;
	}

	@Column(name = "BLOQUE")
	public Integer getBloque() {
		return this.bloque;
	}

	public void setBloque(Integer bloque) {
		this.bloque = bloque;
	}

	@Column(name = "GERANT", length = 30)
	public String getGerant() {
		return this.gerant;
	}

	public void setGerant(String gerant) {
		this.gerant = gerant;
	}

	@Column(name = "STATUS")
	public Integer getStatus() {
		return this.status;
	}

	public void setStatus(Integer status) {
		this.status = status;
	}

	@Column(name = "INFORMATIQUE", nullable = false)
	public int getInformatique() {
		return this.informatique;
	}

	public void setInformatique(int informatique) {
		this.informatique = informatique;
	}

	@Column(name = "NBR_LIVRAISON")
	public Integer getNbrLivraison() {
		return this.nbrLivraison;
	}

	public void setNbrLivraison(Integer nbrLivraison) {
		this.nbrLivraison = nbrLivraison;
	}

	@Column(name = "CA_ANNEE_PREC", precision = 12)
	public BigDecimal getCaAnneePrec() {
		return this.caAnneePrec;
	}

	public void setCaAnneePrec(BigDecimal caAnneePrec) {
		this.caAnneePrec = caAnneePrec;
	}

	@Column(name = "CA_ANNEE", precision = 12)
	public BigDecimal getCaAnnee() {
		return this.caAnnee;
	}

	public void setCaAnnee(BigDecimal caAnnee) {
		this.caAnnee = caAnnee;
	}

	@Column(name = "CA_MOIS", precision = 10)
	public BigDecimal getCaMois() {
		return this.caMois;
	}

	public void setCaMois(BigDecimal caMois) {
		this.caMois = caMois;
	}

	@Column(name = "ENCOURS", precision = 12)
	public BigDecimal getEncours() {
		return this.encours;
	}

	public void setEncours(BigDecimal encours) {
		this.encours = encours;
	}

	@Column(name = "GERER_STOCK")
	public Integer getGererStock() {
		return this.gererStock;
	}

	public void setGererStock(Integer gererStock) {
		this.gererStock = gererStock;
	}

	@Column(name = "NOM_MAGASIN", length = 50)
	public String getNomMagasin() {
		return this.nomMagasin;
	}

	public void setNomMagasin(String nomMagasin) {
		this.nomMagasin = nomMagasin;
	}

	@Column(name = "OBSERVATIONS", length = 100)
	public String getObservations() {
		return this.observations;
	}

	public void setObservations(String observations) {
		this.observations = observations;
	}

	@Column(name = "POURCENTAGE", precision = 5)
	public BigDecimal getPourcentage() {
		return this.pourcentage;
	}

	public void setPourcentage(BigDecimal pourcentage) {
		this.pourcentage = pourcentage;
	}

	@Column(name = "PRIORITE")
	public Integer getPriorite() {
		return this.priorite;
	}

	public void setPriorite(Integer priorite) {
		this.priorite = priorite;
	}

	@Column(name = "TYPE_FACTURATION", nullable = false)
	public int getTypeFacturation() {
		return this.typeFacturation;
	}

	public void setTypeFacturation(int typeFacturation) {
		this.typeFacturation = typeFacturation;
	}

	@Column(name = "SUPERFICIE", precision = 7)
	public BigDecimal getSuperficie() {
		return this.superficie;
	}

	public void setSuperficie(BigDecimal superficie) {
		this.superficie = superficie;
	}

	@Column(name = "num_compte", precision = 10, scale = 0)
	public Long getNumCompte() {
		return this.numCompte;
	}

	public void setNumCompte(Long numCompte) {
		this.numCompte = numCompte;
	}

	@Column(name = "num_representant", precision = 18, scale = 0)
	public Long getNumRepresentant() {
		return this.numRepresentant;
	}

	public void setNumRepresentant(Long numRepresentant) {
		this.numRepresentant = numRepresentant;
	}

	@Column(name = "OS_SERIAL_NUMBER")
	public String getOsSerialNumber() {
		return this.osSerialNumber;
	}

	public void setOsSerialNumber(String osSerialNumber) {
		this.osSerialNumber = osSerialNumber;
	}

	@Column(name = "DISK_SERIAL_NUMBER")
	public String getDiskSerialNumber() {
		return this.diskSerialNumber;
	}

	public void setDiskSerialNumber(String diskSerialNumber) {
		this.diskSerialNumber = diskSerialNumber;
	}

	@Column(name = "SOFT_CODE")
	public String getSoftCode() {
		return this.softCode;
	}

	public void setSoftCode(String softCode) {
		this.softCode = softCode;
	}

	@Column(name = "REGION", length = 50)
	public String getRegion() {
		return this.region;
	}

	public void setRegion(String region) {
		this.region = region;
	}

	@Column(name = "LOCALITE", length = 50)
	public String getLocalite() {
		return this.localite;
	}

	public void setLocalite(String localite) {
		this.localite = localite;
	}

	@Column(name = "MOBILE", length = 20)
	public String getMobile() {
		return this.mobile;
	}

	public void setMobile(String mobile) {
		this.mobile = mobile;
	}

	@Column(name = "PREFIXE_CODE_CMD", length = 10)
	public String getPrefixeCodeCmd() {
		return this.prefixeCodeCmd;
	}

	public void setPrefixeCodeCmd(String prefixeCodeCmd) {
		this.prefixeCodeCmd = prefixeCodeCmd;
	}

	@Column(name = "COMPTEUR_CODE_CMD", length = 7)
	public String getCompteurCodeCmd() {
		return this.compteurCodeCmd;
	}

	public void setCompteurCodeCmd(String compteurCodeCmd) {
		this.compteurCodeCmd = compteurCodeCmd;
	}

	@Column(name = "PREFIXE_CODE_LIV", length = 10)
	public String getPrefixeCodeLiv() {
		return this.prefixeCodeLiv;
	}

	public void setPrefixeCodeLiv(String prefixeCodeLiv) {
		this.prefixeCodeLiv = prefixeCodeLiv;
	}

	@Column(name = "COMPTEUR_CODE_LIV", length = 7)
	public String getCompteurCodeLiv() {
		return this.compteurCodeLiv;
	}

	public void setCompteurCodeLiv(String compteurCodeLiv) {
		this.compteurCodeLiv = compteurCodeLiv;
	}

	@Column(name = "PREFIXE_CODE_FAC", length = 10)
	public String getPrefixeCodeFac() {
		return this.prefixeCodeFac;
	}

	public void setPrefixeCodeFac(String prefixeCodeFac) {
		this.prefixeCodeFac = prefixeCodeFac;
	}

	@Column(name = "COMPTEUR_CODE_FAC", length = 7)
	public String getCompteurCodeFac() {
		return this.compteurCodeFac;
	}

	public void setCompteurCodeFac(String compteurCodeFac) {
		this.compteurCodeFac = compteurCodeFac;
	}

	@Column(name = "PREFIXE_CODE_REG", length = 10)
	public String getPrefixeCodeReg() {
		return this.prefixeCodeReg;
	}

	public void setPrefixeCodeReg(String prefixeCodeReg) {
		this.prefixeCodeReg = prefixeCodeReg;
	}

	@Column(name = "COMPTEUR_CODE_REG", length = 7)
	public String getCompteurCodeReg() {
		return this.compteurCodeReg;
	}

	public void setCompteurCodeReg(String compteurCodeReg) {
		this.compteurCodeReg = compteurCodeReg;
	}

	@Column(name = "PREFIXE_CODE_RET", length = 10)
	public String getPrefixeCodeRet() {
		return this.prefixeCodeRet;
	}

	public void setPrefixeCodeRet(String prefixeCodeRet) {
		this.prefixeCodeRet = prefixeCodeRet;
	}

	@Column(name = "COMPTEUR_CODE_RET", length = 7)
	public String getCompteurCodeRet() {
		return this.compteurCodeRet;
	}

	public void setCompteurCodeRet(String compteurCodeRet) {
		this.compteurCodeRet = compteurCodeRet;
	}

	@Column(name = "PREFIXE_CODE_AVR", length = 10)
	public String getPrefixeCodeAvr() {
		return this.prefixeCodeAvr;
	}

	public void setPrefixeCodeAvr(String prefixeCodeAvr) {
		this.prefixeCodeAvr = prefixeCodeAvr;
	}

	@Column(name = "COMPTEUR_CODE_AVR", length = 7)
	public String getCompteurCodeAvr() {
		return this.compteurCodeAvr;
	}

	public void setCompteurCodeAvr(String compteurCodeAvr) {
		this.compteurCodeAvr = compteurCodeAvr;
	}

	@Column(name = "PREFIXE_CODE_ECH", length = 10)
	public String getPrefixeCodeEch() {
		return this.prefixeCodeEch;
	}

	public void setPrefixeCodeEch(String prefixeCodeEch) {
		this.prefixeCodeEch = prefixeCodeEch;
	}

	@Column(name = "COMPTEUR_CODE_ECH", length = 7)
	public String getCompteurCodeEch() {
		return this.compteurCodeEch;
	}

	public void setCompteurCodeEch(String compteurCodeEch) {
		this.compteurCodeEch = compteurCodeEch;
	}

	@Column(name = "VENTE_HT", nullable = false)
	public int getVenteHt() {
		return this.venteHt;
	}

	public void setVenteHt(int venteHt) {
		this.venteHt = venteHt;
	}

	@Column(name = "PRIX_VNT_CAT_MAG", nullable = false)
	public int getPrixVntCatMag() {
		return this.prixVntCatMag;
	}

	public void setPrixVntCatMag(int prixVntCatMag) {
		this.prixVntCatMag = prixVntCatMag;
	}

	@Column(name = "REG_MULTI_DEVISE", nullable = false)
	public int getRegMultiDevise() {
		return this.regMultiDevise;
	}

	public void setRegMultiDevise(int regMultiDevise) {
		this.regMultiDevise = regMultiDevise;
	}

	@Column(name = "RENDU_MULTI_DEVISE", nullable = false)
	public int getRenduMultiDevise() {
		return this.renduMultiDevise;
	}

	public void setRenduMultiDevise(int renduMultiDevise) {
		this.renduMultiDevise = renduMultiDevise;
	}

	@Column(name = "NUM_REGION")
	public Integer getNumRegion() {
		return this.numRegion;
	}

	public void setNumRegion(Integer numRegion) {
		this.numRegion = numRegion;
	}

	@Column(name = "NUM_LOCALITE")
	public Integer getNumLocalite() {
		return this.numLocalite;
	}

	public void setNumLocalite(Integer numLocalite) {
		this.numLocalite = numLocalite;
	}

	@Column(name = "NUM_VILLE")
	public Integer getNumVille() {
		return this.numVille;
	}

	public void setNumVille(Integer numVille) {
		this.numVille = numVille;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "DATE_OUVERTURE", length = 23)
	public Date getDateOuverture() {
		return this.dateOuverture;
	}

	public void setDateOuverture(Date dateOuverture) {
		this.dateOuverture = dateOuverture;
	}

	@Column(name = "num_compte_auxiliaire", precision = 18, scale = 0)
	public Long getNumCompteAuxiliaire() {
		return this.numCompteAuxiliaire;
	}

	public void setNumCompteAuxiliaire(Long numCompteAuxiliaire) {
		this.numCompteAuxiliaire = numCompteAuxiliaire;
	}

	@Column(name = "UPDATE_BASE_POS")
	public Integer getUpdateBasePos() {
		return this.updateBasePos;
	}

	public void setUpdateBasePos(Integer updateBasePos) {
		this.updateBasePos = updateBasePos;
	}

	@Column(name = "UPDATE_PRG_POS")
	public Integer getUpdatePrgPos() {
		return this.updatePrgPos;
	}

	public void setUpdatePrgPos(Integer updatePrgPos) {
		this.updatePrgPos = updatePrgPos;
	}

	@Column(name = "PHOTO_MAGASIN")
	public String getPhotoMagasin() {
		return this.photoMagasin;
	}

	public void setPhotoMagasin(String photoMagasin) {
		this.photoMagasin = photoMagasin;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "DATE_FERMETURE", length = 23)
	public Date getDateFermeture() {
		return this.dateFermeture;
	}

	public void setDateFermeture(Date dateFermeture) {
		this.dateFermeture = dateFermeture;
	}

	@Column(name = "COORD_LONGITUDE", precision = 18, scale = 10)
	public BigDecimal getCoordLongitude() {
		return this.coordLongitude;
	}

	public void setCoordLongitude(BigDecimal coordLongitude) {
		this.coordLongitude = coordLongitude;
	}

	@Column(name = "COORD_LATITUDE", precision = 18, scale = 10)
	public BigDecimal getCoordLatitude() {
		return this.coordLatitude;
	}

	public void setCoordLatitude(BigDecimal coordLatitude) {
		this.coordLatitude = coordLatitude;
	}

	@Column(name = "ENTREPOT")
	public Integer getEntrepot() {
		return this.entrepot;
	}

	public void setEntrepot(Integer entrepot) {
		this.entrepot = entrepot;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "DATE_SURFACE_EGALE", length = 23)
	public Date getDateSurfaceEgale() {
		return this.dateSurfaceEgale;
	}

	public void setDateSurfaceEgale(Date dateSurfaceEgale) {
		this.dateSurfaceEgale = dateSurfaceEgale;
	}

	@Column(name = "Gere_car_manuel")
	public Integer getGereCarManuel() {
		return this.gereCarManuel;
	}

	public void setGereCarManuel(Integer gereCarManuel) {
		this.gereCarManuel = gereCarManuel;
	}

	@Column(name = "ICE")
	public String getIce() {
		return this.ice;
	}

	public void setIce(String ice) {
		this.ice = ice;
	}

}
