package ma.sofisoft.cam2020ws.entity;
// Generated 15 nov. 2019 10:03:37 by Hibernate Tools 4.3.5.Final

import java.math.BigDecimal;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.JoinColumns;
import javax.persistence.ManyToOne;
import javax.persistence.MapsId;
import javax.persistence.OneToOne;
import javax.persistence.PrimaryKeyJoinColumn;
import javax.persistence.PrimaryKeyJoinColumns;
import javax.persistence.Table;

import org.hibernate.annotations.Cascade;

import com.fasterxml.jackson.annotation.JsonIgnore;

/**
 * LineVenteDirect generated by hbm2java
 */
@Entity
@Table(name = "LINE_VENTE_DIRECT")
public class LineVenteDirect implements java.io.Serializable {

	private LineVenteDirectId id;
	private int numProduit;
	private int numMvt;
	private BigDecimal quantite;
	@JsonIgnore private BigDecimal bruteht;
	@JsonIgnore private BigDecimal tauxTva;
	@JsonIgnore private String codeSaisie;
	@JsonIgnore private BigDecimal reste;
	@JsonIgnore private Integer status;
	@JsonIgnore private BigDecimal tauxRemise;
	@JsonIgnore private BigDecimal erreurCaisse;
	@JsonIgnore private BigDecimal mntcommission;
	@JsonIgnore private BigDecimal mntremisepromo;
	@JsonIgnore private Long numDims;
	private BigDecimal prixVente;
	@JsonIgnore private Long numVendeur;
	@JsonIgnore private Long numPromotion;
	@JsonIgnore private Long numListe;
	@JsonIgnore private BigDecimal qteNegative;
	@JsonIgnore private BigDecimal pmp;
	@JsonIgnore private String codePromo;
	@JsonIgnore private Integer typePromo;
	@JsonIgnore private Integer statusReassort;
	@JsonIgnore private BigDecimal resteReassort;
	@JsonIgnore private long lieuSaisie;
	@JsonIgnore private String typeMvt;
	@JsonIgnore private int livre;
	@JsonIgnore private BigDecimal quantiteDedResa;
	@JsonIgnore private BigDecimal mntremisepromoPays;
	@JsonIgnore private BigDecimal prixVentePays;
	@JsonIgnore private BigDecimal prixRevient;
	@JsonIgnore private String codeAction;
	@JsonIgnore private String codePromoSuiv;
	@JsonIgnore private String codePromoPrec;
	@JsonIgnore private String numComposant;
	@JsonIgnore private String codeLot;
	@JsonIgnore private BigDecimal tauxRemisePied;
	@JsonIgnore private Long numLigneLm;
	@JsonIgnore private Long lieuSaisieLm;
	//@JsonIgnore private String codeUtilisateurForcer;
	
	private StkVenteDirecte stkVenteDirecte;
	
	private StkProduitsGenerique stkProduitsGenerique;
	
	public LineVenteDirect() {
	}

	public LineVenteDirect(LineVenteDirectId id, int numProduit, int numMvt, long lieuSaisie, String typeMvt,
			int livre) {
		this.id = id;
		this.numProduit = numProduit;
		this.numMvt = numMvt;
		this.lieuSaisie = lieuSaisie;
		this.typeMvt = typeMvt;
		this.livre = livre;
	}
	
	public LineVenteDirect(LineVenteDirectId id, int numProduit, int numMvt, BigDecimal quantite, BigDecimal tauxRemise, BigDecimal prixVente) {
		super();
		this.id = id;
		this.numProduit = numProduit;
		this.numMvt = numMvt;
		this.quantite = quantite;
		this.tauxRemise = tauxRemise;
		this.prixVente = prixVente;
		//this.stkProduitsGenerique = stkProduitsGenerique;
	}

	public LineVenteDirect(LineVenteDirectId id, int numProduit, int numMvt, BigDecimal quantite, BigDecimal bruteht,
			BigDecimal tauxTva, String codeSaisie, BigDecimal reste, Integer status, BigDecimal tauxRemise,
			BigDecimal erreurCaisse, BigDecimal mntcommission, BigDecimal mntremisepromo, Long numDims,
			BigDecimal prixVente, Long numVendeur, Long numPromotion, Long numListe, BigDecimal qteNegative,
			BigDecimal pmp, String codePromo, Integer typePromo, Integer statusReassort, BigDecimal resteReassort,
			long lieuSaisie, String typeMvt, int livre, BigDecimal quantiteDedResa, BigDecimal mntremisepromoPays,
			BigDecimal prixVentePays, BigDecimal prixRevient, String codeAction, String codePromoSuiv,
			String codePromoPrec, String numComposant, String codeLot, BigDecimal tauxRemisePied, Long numLigneLm,
			Long lieuSaisieLm, String codeUtilisateurForcer) {
		this.id = id;
		this.numProduit = numProduit;
		this.numMvt = numMvt;
		this.quantite = quantite;
		this.bruteht = bruteht;
		this.tauxTva = tauxTva;
		this.codeSaisie = codeSaisie;
		this.reste = reste;
		this.status = status;
		this.tauxRemise = tauxRemise;
		this.erreurCaisse = erreurCaisse;
		this.mntcommission = mntcommission;
		this.mntremisepromo = mntremisepromo;
		this.numDims = numDims;
		this.prixVente = prixVente;
		this.numVendeur = numVendeur;
		this.numPromotion = numPromotion;
		this.numListe = numListe;
		this.qteNegative = qteNegative;
		this.pmp = pmp;
		this.codePromo = codePromo;
		this.typePromo = typePromo;
		this.statusReassort = statusReassort;
		this.resteReassort = resteReassort;
		this.lieuSaisie = lieuSaisie;
		this.typeMvt = typeMvt;
		this.livre = livre;
		this.quantiteDedResa = quantiteDedResa;
		this.mntremisepromoPays = mntremisepromoPays;
		this.prixVentePays = prixVentePays;
		this.prixRevient = prixRevient;
		this.codeAction = codeAction;
		this.codePromoSuiv = codePromoSuiv;
		this.codePromoPrec = codePromoPrec;
		this.numComposant = numComposant;
		this.codeLot = codeLot;
		this.tauxRemisePied = tauxRemisePied;
		this.numLigneLm = numLigneLm;
		this.lieuSaisieLm = lieuSaisieLm;
		//this.codeUtilisateurForcer = codeUtilisateurForcer;
	}

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "numLigneMouvement", column = @Column(name = "NUM_LIGNE_MOUVEMENT", nullable = false)),
			@AttributeOverride(name = "numMagasin", column = @Column(name = "NUM_MAGASIN", nullable = false)) })
	public LineVenteDirectId getId() {
		return this.id;
	}

	public void setId(LineVenteDirectId id) {
		this.id = id;
	}

	@Column(name = "NUM_PRODUIT", nullable = false)
	public int getNumProduit() {
		return this.numProduit;
	}

	public void setNumProduit(int numProduit) {
		this.numProduit = numProduit;
	}

	@Column(name = "NUM_MVT", nullable = false)
	public int getNumMvt() {
		return this.numMvt;
	}

	public void setNumMvt(int numMvt) {
		this.numMvt = numMvt;
	}

	@Column(name = "QUANTITE", precision = 18, scale = 5)
	public BigDecimal getQuantite() {
		return this.quantite;
	}

	public void setQuantite(BigDecimal quantite) {
		this.quantite = quantite;
	}

	@Column(name = "BRUTEHT", precision = 10)
	public BigDecimal getBruteht() {
		return this.bruteht;
	}

	public void setBruteht(BigDecimal bruteht) {
		this.bruteht = bruteht;
	}

	@Column(name = "TAUX_TVA", precision = 10)
	public BigDecimal getTauxTva() {
		return this.tauxTva;
	}

	public void setTauxTva(BigDecimal tauxTva) {
		this.tauxTva = tauxTva;
	}

	@Column(name = "CODE_SAISIE")
	public String getCodeSaisie() {
		return this.codeSaisie;
	}

	public void setCodeSaisie(String codeSaisie) {
		this.codeSaisie = codeSaisie;
	}

	@Column(name = "RESTE", precision = 10)
	public BigDecimal getReste() {
		return this.reste;
	}

	public void setReste(BigDecimal reste) {
		this.reste = reste;
	}

	@Column(name = "STATUS")
	public Integer getStatus() {
		return this.status;
	}

	public void setStatus(Integer status) {
		this.status = status;
	}

	@Column(name = "TAUX_REMISE", precision = 5)
	public BigDecimal getTauxRemise() {
		return this.tauxRemise;
	}

	public void setTauxRemise(BigDecimal tauxRemise) {
		this.tauxRemise = tauxRemise;
	}

	@Column(name = "ERREUR_CAISSE", precision = 10)
	public BigDecimal getErreurCaisse() {
		return this.erreurCaisse;
	}

	public void setErreurCaisse(BigDecimal erreurCaisse) {
		this.erreurCaisse = erreurCaisse;
	}

	@Column(name = "MNTCOMMISSION", precision = 10)
	public BigDecimal getMntcommission() {
		return this.mntcommission;
	}

	public void setMntcommission(BigDecimal mntcommission) {
		this.mntcommission = mntcommission;
	}

	@Column(name = "MNTREMISEPROMO", precision = 10)
	public BigDecimal getMntremisepromo() {
		return this.mntremisepromo;
	}

	public void setMntremisepromo(BigDecimal mntremisepromo) {
		this.mntremisepromo = mntremisepromo;
	}

	@Column(name = "NUM_DIMS", precision = 10, scale = 0)
	public Long getNumDims() {
		return this.numDims;
	}

	public void setNumDims(Long numDims) {
		this.numDims = numDims;
	}

	@Column(name = "PRIX_VENTE", precision = 10)
	public BigDecimal getPrixVente() {
		return this.prixVente;
	}

	public void setPrixVente(BigDecimal prixVente) {
		this.prixVente = prixVente;
	}

	@Column(name = "NUM_VENDEUR", precision = 10, scale = 0)
	public Long getNumVendeur() {
		return this.numVendeur;
	}

	public void setNumVendeur(Long numVendeur) {
		this.numVendeur = numVendeur;
	}

	@Column(name = "NUM_PROMOTION", precision = 10, scale = 0)
	public Long getNumPromotion() {
		return this.numPromotion;
	}

	public void setNumPromotion(Long numPromotion) {
		this.numPromotion = numPromotion;
	}

	@Column(name = "NUM_LISTE", precision = 10, scale = 0)
	public Long getNumListe() {
		return this.numListe;
	}

	public void setNumListe(Long numListe) {
		this.numListe = numListe;
	}

	@Column(name = "QTE_NEGATIVE", precision = 10)
	public BigDecimal getQteNegative() {
		return this.qteNegative;
	}

	public void setQteNegative(BigDecimal qteNegative) {
		this.qteNegative = qteNegative;
	}

	@Column(name = "PMP", precision = 18)
	public BigDecimal getPmp() {
		return this.pmp;
	}

	public void setPmp(BigDecimal pmp) {
		this.pmp = pmp;
	}

	@Column(name = "CODE_PROMO")
	public String getCodePromo() {
		return this.codePromo;
	}

	public void setCodePromo(String codePromo) {
		this.codePromo = codePromo;
	}

	@Column(name = "TYPE_PROMO")
	public Integer getTypePromo() {
		return this.typePromo;
	}

	public void setTypePromo(Integer typePromo) {
		this.typePromo = typePromo;
	}

	@Column(name = "STATUS_REASSORT")
	public Integer getStatusReassort() {
		return this.statusReassort;
	}

	public void setStatusReassort(Integer statusReassort) {
		this.statusReassort = statusReassort;
	}

	@Column(name = "RESTE_REASSORT", precision = 10)
	public BigDecimal getResteReassort() {
		return this.resteReassort;
	}

	public void setResteReassort(BigDecimal resteReassort) {
		this.resteReassort = resteReassort;
	}

	@Column(name = "LIEU_SAISIE", nullable = false, precision = 18, scale = 0)
	public long getLieuSaisie() {
		return this.lieuSaisie;
	}

	public void setLieuSaisie(long lieuSaisie) {
		this.lieuSaisie = lieuSaisie;
	}

	@Column(name = "TYPE_MVT", nullable = false, length = 10)
	public String getTypeMvt() {
		return this.typeMvt;
	}

	public void setTypeMvt(String typeMvt) {
		this.typeMvt = typeMvt;
	}

	@Column(name = "LIVRE", nullable = false)
	public int getLivre() {
		return this.livre;
	}

	public void setLivre(int livre) {
		this.livre = livre;
	}

	@Column(name = "QUANTITE_DED_RESA", precision = 18)
	public BigDecimal getQuantiteDedResa() {
		return this.quantiteDedResa;
	}

	public void setQuantiteDedResa(BigDecimal quantiteDedResa) {
		this.quantiteDedResa = quantiteDedResa;
	}

	@Column(name = "MNTREMISEPROMO_PAYS", precision = 18)
	public BigDecimal getMntremisepromoPays() {
		return this.mntremisepromoPays;
	}

	public void setMntremisepromoPays(BigDecimal mntremisepromoPays) {
		this.mntremisepromoPays = mntremisepromoPays;
	}

	@Column(name = "PRIX_VENTE_PAYS", precision = 18)
	public BigDecimal getPrixVentePays() {
		return this.prixVentePays;
	}

	public void setPrixVentePays(BigDecimal prixVentePays) {
		this.prixVentePays = prixVentePays;
	}

	@Column(name = "PRIX_REVIENT", precision = 18, scale = 3)
	public BigDecimal getPrixRevient() {
		return this.prixRevient;
	}

	public void setPrixRevient(BigDecimal prixRevient) {
		this.prixRevient = prixRevient;
	}

	@Column(name = "CODE_ACTION", length = 20)
	public String getCodeAction() {
		return this.codeAction;
	}

	public void setCodeAction(String codeAction) {
		this.codeAction = codeAction;
	}

	@Column(name = "CODE_PROMO_SUIV", length = 10)
	public String getCodePromoSuiv() {
		return this.codePromoSuiv;
	}

	public void setCodePromoSuiv(String codePromoSuiv) {
		this.codePromoSuiv = codePromoSuiv;
	}

	@Column(name = "CODE_PROMO_PREC", length = 10)
	public String getCodePromoPrec() {
		return this.codePromoPrec;
	}

	public void setCodePromoPrec(String codePromoPrec) {
		this.codePromoPrec = codePromoPrec;
	}

	@Column(name = "NUM_COMPOSANT", length = 2)
	public String getNumComposant() {
		return this.numComposant;
	}

	public void setNumComposant(String numComposant) {
		this.numComposant = numComposant;
	}

	@Column(name = "CODE_LOT", length = 10)
	public String getCodeLot() {
		return this.codeLot;
	}

	public void setCodeLot(String codeLot) {
		this.codeLot = codeLot;
	}

	@Column(name = "TAUX_REMISE_PIED", precision = 10, scale = 4)
	public BigDecimal getTauxRemisePied() {
		return this.tauxRemisePied;
	}

	public void setTauxRemisePied(BigDecimal tauxRemisePied) {
		this.tauxRemisePied = tauxRemisePied;
	}

	@Column(name = "NUM_LIGNE_LM", precision = 18, scale = 0)
	public Long getNumLigneLm() {
		return this.numLigneLm;
	}

	public void setNumLigneLm(Long numLigneLm) {
		this.numLigneLm = numLigneLm;
	}

	@Column(name = "LIEU_SAISIE_LM", precision = 18, scale = 0)
	public Long getLieuSaisieLm() {
		return this.lieuSaisieLm;
	}

	
	public void setLieuSaisieLm(Long lieuSaisieLm) {
		this.lieuSaisieLm = lieuSaisieLm;
	}

	/*
	@Column(name = "CODE_UTILISATEUR_FORCER")
	public String getCodeUtilisateurForcer() {
		return this.codeUtilisateurForcer;
	}

	public void setCodeUtilisateurForcer(String codeUtilisateurForcer) {
		this.codeUtilisateurForcer = codeUtilisateurForcer;
	}*/
		
	/*@PrimaryKeyJoinColumns(value = {
			@PrimaryKeyJoinColumn(name = "NUM_MVT", referencedColumnName="numMvt"),
			@PrimaryKeyJoinColumn(name = "NUM_MAGASIN", referencedColumnName="numMagasin")
			})*/
	
	//@MapsId("StkVenteDirecteId") fetch = FetchType.LAZY, cascade = CascadeType.ALL
	@JsonIgnore
	@ManyToOne
	@JoinColumns({
		@JoinColumn(name = "NUM_MVT",insertable = false,updatable = false ,nullable = false, referencedColumnName="NUM_MVT"),
		@JoinColumn(name = "NUM_MAGASIN",insertable = false,updatable = false,nullable = false, referencedColumnName="NUM_MAGASIN")
		})	
	public StkVenteDirecte getStkVenteDirecte() {
		return this.stkVenteDirecte;
	}

	public void setStkVenteDirecte(StkVenteDirecte stkVenteDirecte) {
		this.stkVenteDirecte = stkVenteDirecte;
	}
	
	/*@OneToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "NUM_PRODUIT")*/

	@ManyToOne
    @JoinColumn(name = "NUM_PRODUIT",referencedColumnName = "NUM_PRODUIT", insertable= false, updatable = false)
	//@Cascade(value={org.hibernate.annotations.CascadeType.ALL})
	public StkProduitsGenerique getStkProduitsGenerique() {
		return stkProduitsGenerique;
	}

	public void setStkProduitsGenerique(StkProduitsGenerique stkProduitsGenerique) {
		this.stkProduitsGenerique = stkProduitsGenerique;
	}
}
