package ma.sofisoft.cam2020ws.entity;
// Generated 15 nov. 2019 10:03:37 by Hibernate Tools 4.3.5.Final

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * LineVenteDirectId generated by hbm2java
 */
@Embeddable
public class LineVenteDirectId implements java.io.Serializable {

	private int numLigneMouvement;
	private int numMagasin;

	public LineVenteDirectId() {
	}

	public LineVenteDirectId(int numLigneMouvement, int numMagasin) {
		this.numLigneMouvement = numLigneMouvement;
		this.numMagasin = numMagasin;
	}

	@Column(name = "NUM_LIGNE_MOUVEMENT", nullable = false)
	public int getNumLigneMouvement() {
		return this.numLigneMouvement;
	}

	public void setNumLigneMouvement(int numLigneMouvement) {
		this.numLigneMouvement = numLigneMouvement;
	}

	@Column(name = "NUM_MAGASIN", nullable = false)
	public int getNumMagasin() {
		return this.numMagasin;
	}

	public void setNumMagasin(int numMagasin) {
		this.numMagasin = numMagasin;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof LineVenteDirectId))
			return false;
		LineVenteDirectId castOther = (LineVenteDirectId) other;

		return (this.getNumLigneMouvement() == castOther.getNumLigneMouvement())
				&& (this.getNumMagasin() == castOther.getNumMagasin());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getNumLigneMouvement();
		result = 37 * result + this.getNumMagasin();
		return result;
	}

}
