package ma.sofisoft.cam2020ws.entity;
// Generated 15 nov. 2019 10:03:37 by Hibernate Tools 4.3.5.Final

import java.io.Serializable;
import java.math.BigDecimal;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.UniqueConstraint;

import com.fasterxml.jackson.annotation.JsonIgnore;

/**
 * StkPrdDim generated by hbm2java
 */
@Entity
@Table(name = "STK_PRD_DIM", uniqueConstraints = @UniqueConstraint(columnNames = "CODE_PRODUIT"))
public class StkPrdDim implements java.io.Serializable {

	private long numDims;
	private int numProduit;
	@JsonIgnore private StkProduitsGenerique stkProduitsGenerique;
	private Long numDim2;
	private Long numDim1;
	private Long numDim3;
	private Long numDim4;
	private Integer numLigneDetail;
	private Long numRayon;
	private Long numEtagere;
	private Long numCase;
	private BigDecimal quantite;
	private Integer bloque;
	private Integer bloqueInv;
	private String codeBarre;
	private BigDecimal pmp;
	private BigDecimal prixRevient;
	private BigDecimal stockMax;
	private BigDecimal stockMin;
	private BigDecimal prixVente;
	private String codeProduit;
	private BigDecimal stockInt;
	private BigDecimal pmpInt;
	private BigDecimal prixUnitaire;
	private BigDecimal prixVente1Ht;
	private BigDecimal prixVente1Ttc;
	private Date datePrixVente1;
	private BigDecimal prixVente2Ht;
	private BigDecimal prixVente2Ttc;
	private Date datePrixVente2;
	private BigDecimal prixVente3Ht;
	private BigDecimal prixVente3Ttc;
	private Date datePrixVente3;
	private BigDecimal prixVente4Ht;
	private BigDecimal prixVente4Ttc;
	private Date datePrixVente4;
	private String image;

	public StkPrdDim() {
	}

	public StkPrdDim(long numDims, StkProduitsGenerique stkProduitsGenerique) {
		this.numDims = numDims;
		this.stkProduitsGenerique = stkProduitsGenerique;
	}

	public StkPrdDim(long numDims, StkProduitsGenerique stkProduitsGenerique, Long numDim2, Long numDim1, Long numDim3,
			Long numDim4, Integer numLigneDetail, Long numRayon, Long numEtagere, Long numCase, BigDecimal quantite,
			Integer bloque, Integer bloqueInv, String codeBarre, BigDecimal pmp, BigDecimal prixRevient,
			BigDecimal stockMax, BigDecimal stockMin, BigDecimal prixVente, String codeProduit,
			BigDecimal stockInt, BigDecimal pmpInt, BigDecimal prixUnitaire, BigDecimal prixVente1Ht,
			BigDecimal prixVente1Ttc, Date datePrixVente1, BigDecimal prixVente2Ht, BigDecimal prixVente2Ttc,
			Date datePrixVente2, BigDecimal prixVente3Ht, BigDecimal prixVente3Ttc, Date datePrixVente3,
			BigDecimal prixVente4Ht, BigDecimal prixVente4Ttc, Date datePrixVente4, String image) {
		this.numDims = numDims;
		this.stkProduitsGenerique = stkProduitsGenerique;
		this.numDim2 = numDim2;
		this.numDim1 = numDim1;
		this.numDim3 = numDim3;
		this.numDim4 = numDim4;
		this.numLigneDetail = numLigneDetail;
		this.numRayon = numRayon;
		this.numEtagere = numEtagere;
		this.numCase = numCase;
		this.quantite = quantite;
		this.bloque = bloque;
		this.bloqueInv = bloqueInv;
		this.codeBarre = codeBarre;
		this.pmp = pmp;
		this.prixRevient = prixRevient;
		this.stockMax = stockMax;
		this.stockMin = stockMin;
		this.prixVente = prixVente;
		this.codeProduit = codeProduit;
		this.stockInt = stockInt;
		this.pmpInt = pmpInt;
		this.prixUnitaire = prixUnitaire;
		this.prixVente1Ht = prixVente1Ht;
		this.prixVente1Ttc = prixVente1Ttc;
		this.datePrixVente1 = datePrixVente1;
		this.prixVente2Ht = prixVente2Ht;
		this.prixVente2Ttc = prixVente2Ttc;
		this.datePrixVente2 = datePrixVente2;
		this.prixVente3Ht = prixVente3Ht;
		this.prixVente3Ttc = prixVente3Ttc;
		this.datePrixVente3 = datePrixVente3;
		this.prixVente4Ht = prixVente4Ht;
		this.prixVente4Ttc = prixVente4Ttc;
		this.datePrixVente4 = datePrixVente4;
		this.image = image;
	}

	@Id
	@Column(name = "NUM_DIMS", unique = true, nullable = false, precision = 10, scale = 0)
	public long getNumDims() {
		return this.numDims;
	}

	public void setNumDims(long numDims) {
		this.numDims = numDims;
	}
	
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "NUM_PRODUIT", nullable = false)
	public StkProduitsGenerique getStkProduitsGenerique() {
		return this.stkProduitsGenerique;
	}

	public void setStkProduitsGenerique(StkProduitsGenerique stkProduitsGenerique) {
		this.stkProduitsGenerique = stkProduitsGenerique;
	}

	@Column(name = "NUM_DIM2", precision = 10, scale = 0)
	public Long getNumDim2() {
		return this.numDim2;
	}

	public void setNumDim2(Long numDim2) {
		this.numDim2 = numDim2;
	}

	@Column(name = "NUM_DIM1", precision = 10, scale = 0)
	public Long getNumDim1() {
		return this.numDim1;
	}

	public void setNumDim1(Long numDim1) {
		this.numDim1 = numDim1;
	}

	@Column(name = "NUM_DIM3", precision = 10, scale = 0)
	public Long getNumDim3() {
		return this.numDim3;
	}

	public void setNumDim3(Long numDim3) {
		this.numDim3 = numDim3;
	}

	@Column(name = "NUM_DIM4", precision = 10, scale = 0)
	public Long getNumDim4() {
		return this.numDim4;
	}

	public void setNumDim4(Long numDim4) {
		this.numDim4 = numDim4;
	}

	@Column(name = "NUM_LIGNE_DETAIL")
	public Integer getNumLigneDetail() {
		return this.numLigneDetail;
	}

	public void setNumLigneDetail(Integer numLigneDetail) {
		this.numLigneDetail = numLigneDetail;
	}

	@Column(name = "NUM_RAYON", precision = 10, scale = 0)
	public Long getNumRayon() {
		return this.numRayon;
	}

	public void setNumRayon(Long numRayon) {
		this.numRayon = numRayon;
	}

	@Column(name = "NUM_ETAGERE", precision = 10, scale = 0)
	public Long getNumEtagere() {
		return this.numEtagere;
	}

	public void setNumEtagere(Long numEtagere) {
		this.numEtagere = numEtagere;
	}

	@Column(name = "NUM_CASE", precision = 10, scale = 0)
	public Long getNumCase() {
		return this.numCase;
	}

	public void setNumCase(Long numCase) {
		this.numCase = numCase;
	}

	@Column(name = "QUANTITE", precision = 10)
	public BigDecimal getQuantite() {
		return this.quantite;
	}

	public void setQuantite(BigDecimal quantite) {
		this.quantite = quantite;
	}

	@Column(name = "BLOQUE")
	public Integer getBloque() {
		return this.bloque;
	}

	public void setBloque(Integer bloque) {
		this.bloque = bloque;
	}

	@Column(name = "BLOQUE_INV")
	public Integer getBloqueInv() {
		return this.bloqueInv;
	}

	public void setBloqueInv(Integer bloqueInv) {
		this.bloqueInv = bloqueInv;
	}

	@Column(name = "CODE_BARRE")
	public String getCodeBarre() {
		return this.codeBarre;
	}

	public void setCodeBarre(String codeBarre) {
		this.codeBarre = codeBarre;
	}

	@Column(name = "PMP", precision = 11)
	public BigDecimal getPmp() {
		return this.pmp;
	}

	public void setPmp(BigDecimal pmp) {
		this.pmp = pmp;
	}

	@Column(name = "PRIX_REVIENT", precision = 13)
	public BigDecimal getPrixRevient() {
		return this.prixRevient;
	}

	public void setPrixRevient(BigDecimal prixRevient) {
		this.prixRevient = prixRevient;
	}

	@Column(name = "STOCK_MAX", precision = 10)
	public BigDecimal getStockMax() {
		return this.stockMax;
	}

	public void setStockMax(BigDecimal stockMax) {
		this.stockMax = stockMax;
	}

	@Column(name = "STOCK_MIN", precision = 10)
	public BigDecimal getStockMin() {
		return this.stockMin;
	}

	public void setStockMin(BigDecimal stockMin) {
		this.stockMin = stockMin;
	}

	@Column(name = "PRIX_VENTE", precision = 10)
	public BigDecimal getPrixVente() {
		return this.prixVente;
	}

	public void setPrixVente(BigDecimal prixVente) {
		this.prixVente = prixVente;
	}

	@Column(name = "CODE_PRODUIT", unique = true)
	public String getCodeProduit() {
		return this.codeProduit;
	}

	public void setCodeProduit(String codeProduit) {
		this.codeProduit = codeProduit;
	}

	@Column(name = "STOCK_INT", precision = 10)
	public BigDecimal getStockInt() {
		return this.stockInt;
	}

	public void setStockInt(BigDecimal stockInt) {
		this.stockInt = stockInt;
	}

	@Column(name = "PMP_INT", precision = 11)
	public BigDecimal getPmpInt() {
		return this.pmpInt;
	}

	public void setPmpInt(BigDecimal pmpInt) {
		this.pmpInt = pmpInt;
	}

	@Column(name = "PRIX_UNITAIRE", precision = 18, scale = 3)
	public BigDecimal getPrixUnitaire() {
		return this.prixUnitaire;
	}

	public void setPrixUnitaire(BigDecimal prixUnitaire) {
		this.prixUnitaire = prixUnitaire;
	}

	@Column(name = "PRIX_VENTE1_HT", precision = 10)
	public BigDecimal getPrixVente1Ht() {
		return this.prixVente1Ht;
	}

	public void setPrixVente1Ht(BigDecimal prixVente1Ht) {
		this.prixVente1Ht = prixVente1Ht;
	}

	@Column(name = "PRIX_VENTE1_TTC", precision = 10)
	public BigDecimal getPrixVente1Ttc() {
		return this.prixVente1Ttc;
	}

	public void setPrixVente1Ttc(BigDecimal prixVente1Ttc) {
		this.prixVente1Ttc = prixVente1Ttc;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "DATE_PRIX_VENTE1", length = 23)
	public Date getDatePrixVente1() {
		return this.datePrixVente1;
	}

	public void setDatePrixVente1(Date datePrixVente1) {
		this.datePrixVente1 = datePrixVente1;
	}

	@Column(name = "PRIX_VENTE2_HT", precision = 10)
	public BigDecimal getPrixVente2Ht() {
		return this.prixVente2Ht;
	}

	public void setPrixVente2Ht(BigDecimal prixVente2Ht) {
		this.prixVente2Ht = prixVente2Ht;
	}

	@Column(name = "PRIX_VENTE2_TTC", precision = 10)
	public BigDecimal getPrixVente2Ttc() {
		return this.prixVente2Ttc;
	}

	public void setPrixVente2Ttc(BigDecimal prixVente2Ttc) {
		this.prixVente2Ttc = prixVente2Ttc;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "DATE_PRIX_VENTE2", length = 23)
	public Date getDatePrixVente2() {
		return this.datePrixVente2;
	}

	public void setDatePrixVente2(Date datePrixVente2) {
		this.datePrixVente2 = datePrixVente2;
	}

	@Column(name = "PRIX_VENTE3_HT", precision = 10)
	public BigDecimal getPrixVente3Ht() {
		return this.prixVente3Ht;
	}

	public void setPrixVente3Ht(BigDecimal prixVente3Ht) {
		this.prixVente3Ht = prixVente3Ht;
	}

	@Column(name = "PRIX_VENTE3_TTC", precision = 10)
	public BigDecimal getPrixVente3Ttc() {
		return this.prixVente3Ttc;
	}

	public void setPrixVente3Ttc(BigDecimal prixVente3Ttc) {
		this.prixVente3Ttc = prixVente3Ttc;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "DATE_PRIX_VENTE3", length = 23)
	public Date getDatePrixVente3() {
		return this.datePrixVente3;
	}

	public void setDatePrixVente3(Date datePrixVente3) {
		this.datePrixVente3 = datePrixVente3;
	}

	@Column(name = "PRIX_VENTE4_HT", precision = 10)
	public BigDecimal getPrixVente4Ht() {
		return this.prixVente4Ht;
	}

	public void setPrixVente4Ht(BigDecimal prixVente4Ht) {
		this.prixVente4Ht = prixVente4Ht;
	}

	@Column(name = "PRIX_VENTE4_TTC", precision = 10)
	public BigDecimal getPrixVente4Ttc() {
		return this.prixVente4Ttc;
	}

	public void setPrixVente4Ttc(BigDecimal prixVente4Ttc) {
		this.prixVente4Ttc = prixVente4Ttc;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "DATE_PRIX_VENTE4", length = 23)
	public Date getDatePrixVente4() {
		return this.datePrixVente4;
	}

	public void setDatePrixVente4(Date datePrixVente4) {
		this.datePrixVente4 = datePrixVente4;
	}

	@Column(name = "IMAGE")
	public String getImage() {
		return this.image;
	}

	public void setImage(String image) {
		this.image = image;
	}
	
	
	@Column(name = "NUM_PRODUIT", nullable = false, insertable=false, updatable=false, precision = 10, scale = 0)
	public int getNumProduit() {
		return numProduit;
	}

	public void setNumProduit(int numProduit) {
		this.numProduit = numProduit;
	}

}
