package ma.sofisoft.cam2020ws.entity;
// Generated 15 nov. 2019 10:03:37 by Hibernate Tools 4.3.5.Final

import java.io.Serializable;
import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.Date;
import java.util.HashSet;
import java.util.List;
import java.util.Set;

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.JoinColumns;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.Transient;
import javax.sound.sampled.Line;

import org.hibernate.annotations.CreationTimestamp;
import org.hibernate.annotations.Fetch;
import org.hibernate.annotations.FetchMode;
import org.hibernate.annotations.Immutable;
import org.springframework.data.annotation.CreatedDate;
import org.springframework.format.annotation.DateTimeFormat;

import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.databind.annotation.JsonSerialize;

/**
 * StkVenteDirecte generated by hbm2java
 */
@JsonSerialize
@Entity
@Table(name = "STK_VENTE_DIRECTE")
@Immutable
public class StkVenteDirecte implements java.io.Serializable {

	private StkVenteDirecteId id;
	//long numVendeur;
	@JsonIgnore private long numVendeur;
	@JsonIgnore private long codeDepot;
	private Date dateMvt;
	@JsonIgnore private BigDecimal montantHt;
	@JsonIgnore private BigDecimal montantRemise;
	@JsonIgnore private BigDecimal montantTva;
	private String numVente;
	@JsonIgnore private Long numUtilisateur;
	@JsonIgnore private Integer typevente;
	private BigDecimal montantTtc;
	@JsonIgnore private BigDecimal mntremisepromo;
	@JsonIgnore private BigDecimal erreurcaisse;
	private BigDecimal tauxRemise;
	@JsonIgnore private Long numClient;
	@JsonIgnore private Short numCaisse;
	@JsonIgnore private Long numVenteRetour;
	@JsonIgnore private BigDecimal montantReste;
	@JsonIgnore private BigDecimal acompte;
	@JsonIgnore private String observation;
	@JsonIgnore private long numJournee;
	@JsonIgnore private BigDecimal montantRendu;
	@JsonIgnore private Long numAvoirPromo;
	@JsonIgnore private Long numMagasinClient;
	@JsonIgnore private Long numPromoProvoque;
	@JsonIgnore private long lieuSaisie;
	@JsonIgnore private String typeMvt;
	@JsonIgnore private int majStk;
	private int sensStk;
	@JsonIgnore private int majResa;
	@JsonIgnore private int import_;
	@JsonIgnore private int dedResa;
	@JsonIgnore private int dedLivr;
	@JsonIgnore private Long numMotif;
	@JsonIgnore private BigDecimal montantHtPays;
	@JsonIgnore private BigDecimal montantRemisePays;
	@JsonIgnore private BigDecimal montantTvaPays;
	@JsonIgnore private BigDecimal montantTtcPays;
	@JsonIgnore private BigDecimal mntremisepromoPays;
	@JsonIgnore private BigDecimal montantRestePays;
	@JsonIgnore private BigDecimal montantRenduPays;
	@JsonIgnore private Long numDevise;
	@JsonIgnore private BigDecimal tauxDevise;
	@JsonIgnore private Integer uniteDevise;
	@JsonIgnore private String codeRemise;
	@JsonIgnore private Character statusFacture;
	@JsonIgnore private String numFacture;
	@JsonIgnore private Long numJourneeCaissier;
	@JsonIgnore private Date datetimeCreation;
	@JsonIgnore private String codeActionPrincipale;
	@JsonIgnore private BigDecimal droitTimbre;
	@JsonIgnore private String codePlvEncours;
	@JsonIgnore private BigDecimal baseRemise;
	@JsonIgnore private BigDecimal tauxRemiseAccorde;
	@JsonIgnore private String typeTypeMvt;
	@JsonIgnore private String codeUtilisateurAutorise;
	@JsonIgnore private String indexChaises;
	@JsonIgnore private Integer pointsFidelite;
	
	@JsonIgnore private int hour;
	@JsonIgnore private Integer nmbreTicket;
	
	
	private Set<LineVenteDirect> lineVenteDirects = new HashSet<LineVenteDirect>();
	private int numMvt;
	private long numMagasin;

	

	@Column(name = "NUM_MVT", insertable = false,updatable = false ,nullable = false)
	public int getNumMvt() {
		return this.numMvt;
	}

	public void setNumMvt(int numMvt) {
		this.numMvt = numMvt;
	}

	@Column(name = "NUM_MAGASIN", insertable = false,updatable = false ,nullable = false, precision = 10, scale = 0)
	public long getNumMagasin() {
		return this.numMagasin;
	}

	public void setNumMagasin(long numMagasin) {
		this.numMagasin = numMagasin;
	}
		
	public StkVenteDirecte() {
	}

	public StkVenteDirecte(StkVenteDirecteId id, long numVendeur, long codeDepot, String numVente,
			long numJournee, long lieuSaisie, String typeMvt, int majStk, int sensStk, int majResa, int import_,
			int dedResa, int dedLivr) {
		this.id = id;
		this.numVendeur = numVendeur;
		this.codeDepot = codeDepot;
		this.numVente = numVente;
		this.numJournee = numJournee;
		this.lieuSaisie = lieuSaisie;
		this.typeMvt = typeMvt;
		this.majStk = majStk;
		this.sensStk = sensStk;
		this.majResa = majResa;
		this.import_ = import_;
		this.dedResa = dedResa;
		this.dedLivr = dedLivr;
	}
	
	public StkVenteDirecte(StkVenteDirecteId id, 
							Date dateMvt,
							String numVente,
							BigDecimal montantTtc, 
							BigDecimal tauxRemise, 
							int sensStk) {
		this.id = id;
		this.dateMvt = dateMvt;
		this.numVente = numVente;
		this.montantTtc = montantTtc;
		this.tauxRemise = tauxRemise;
		this.sensStk = sensStk;
		//this.lineVenteDirects = lineVenteDirects;
	}

	public StkVenteDirecte(StkVenteDirecteId id, long numVendeur, long codeDepot, Date dateMvt,
			BigDecimal montantHt, BigDecimal montantRemise, BigDecimal montantTva, String numVente, Long numUtilisateur,
			Integer typevente, BigDecimal montantTtc, BigDecimal mntremisepromo, BigDecimal erreurcaisse,
			BigDecimal tauxRemise, Long numClient, Short numCaisse, Long numVenteRetour, BigDecimal montantReste,
			BigDecimal acompte, String observation, long numJournee, BigDecimal montantRendu, Long numAvoirPromo,
			Long numMagasinClient, Long numPromoProvoque, long lieuSaisie, String typeMvt, int majStk, int sensStk,
			int majResa, int import_, int dedResa, int dedLivr, Long numMotif, BigDecimal montantHtPays,
			BigDecimal montantRemisePays, BigDecimal montantTvaPays, BigDecimal montantTtcPays,
			BigDecimal mntremisepromoPays, BigDecimal montantRestePays, BigDecimal montantRenduPays, Long numDevise,
			BigDecimal tauxDevise, Integer uniteDevise, String codeRemise, Character statusFacture, String numFacture,
			Long numJourneeCaissier, Date datetimeCreation, String codeActionPrincipale, BigDecimal droitTimbre,
			String codePlvEncours, BigDecimal baseRemise, BigDecimal tauxRemiseAccorde, String typeTypeMvt,
			 String codeUtilisateurAutorise, String indexChaises, Integer pointsFidelite) {
		this.id = id;
		this.numVendeur = numVendeur;
		this.codeDepot = codeDepot;
		this.dateMvt = dateMvt;
		this.montantHt = montantHt;
		this.montantRemise = montantRemise;
		this.montantTva = montantTva;
		this.numVente = numVente;
		this.numUtilisateur = numUtilisateur;
		this.typevente = typevente;
		this.montantTtc = montantTtc;
		this.mntremisepromo = mntremisepromo;
		this.erreurcaisse = erreurcaisse;
		this.tauxRemise = tauxRemise;
		this.numClient = numClient;
		this.numCaisse = numCaisse;
		this.numVenteRetour = numVenteRetour;
		this.montantReste = montantReste;
		this.acompte = acompte;
		this.observation = observation;
		this.numJournee = numJournee;
		this.montantRendu = montantRendu;
		this.numAvoirPromo = numAvoirPromo;
		this.numMagasinClient = numMagasinClient;
		this.numPromoProvoque = numPromoProvoque;
		this.lieuSaisie = lieuSaisie;
		this.typeMvt = typeMvt;
		this.majStk = majStk;
		this.sensStk = sensStk;
		this.majResa = majResa;
		this.import_ = import_;
		this.dedResa = dedResa;
		this.dedLivr = dedLivr;
		this.numMotif = numMotif;
		this.montantHtPays = montantHtPays;
		this.montantRemisePays = montantRemisePays;
		this.montantTvaPays = montantTvaPays;
		this.montantTtcPays = montantTtcPays;
		this.mntremisepromoPays = mntremisepromoPays;
		this.montantRestePays = montantRestePays;
		this.montantRenduPays = montantRenduPays;
		this.numDevise = numDevise;
		this.tauxDevise = tauxDevise;
		this.uniteDevise = uniteDevise;
		this.codeRemise = codeRemise;
		this.statusFacture = statusFacture;
		this.numFacture = numFacture;
		this.numJourneeCaissier = numJourneeCaissier;
		this.datetimeCreation = datetimeCreation;
		this.codeActionPrincipale = codeActionPrincipale;
		this.droitTimbre = droitTimbre;
		this.codePlvEncours = codePlvEncours;
		this.baseRemise = baseRemise;
		this.tauxRemiseAccorde = tauxRemiseAccorde;
		this.typeTypeMvt = typeTypeMvt;
		this.codeUtilisateurAutorise = codeUtilisateurAutorise;
		this.indexChaises = indexChaises;
		this.pointsFidelite = pointsFidelite;
	}
	
	public StkVenteDirecte(Date dateMvt,BigDecimal MontantTTC, int hour) {
		this.dateMvt = dateMvt;
		this.hour = hour;
		this.montantTtc = MontantTTC;
	}	

	@EmbeddedId
	@AttributeOverrides({ 
		@AttributeOverride(name = "numMvt", column = @Column(name = "NUM_MVT", nullable = false)),
		@AttributeOverride(name = "numMagasin", column = @Column(name = "NUM_MAGASIN", nullable = false, precision = 10, scale = 0))
	})
	public StkVenteDirecteId getId() {
		return this.id;
	}

	public void setId(StkVenteDirecteId id) {
		this.id = id;
	}
	
	//@ManyToOne(fetch = FetchType.LAZY)
	//@JoinColumn(name = "NUM_VENDEUR", nullable = false)
	@Column(name = "NUM_VENDEUR", length = 23)
	public long getVendeurMag() {
		return this.numVendeur;
	}

	public void setVendeurMag(long vendeurMag) {
		this.numVendeur = vendeurMag;
	}

	@Column(name = "CODE_DEPOT", nullable = false, precision = 10, scale = 0)
	public long getCodeDepot() {
		return this.codeDepot;
	}

	public void setCodeDepot(long codeDepot) {
		this.codeDepot = codeDepot;
	}

	@CreationTimestamp
	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "DATE_MVT", length = 23)
	public Date getDateMvt() {
		return dateMvt;
	}

	public void setDateMvt(Date dateMvt) {
		this.dateMvt = dateMvt;
	}

	@Column(name = "MONTANT_HT", precision = 18, scale = 3)
	public BigDecimal getMontantHt() {
		return this.montantHt;
	}

	public void setMontantHt(BigDecimal montantHt) {
		this.montantHt = montantHt;
	}

	@Column(name = "MONTANT_REMISE", precision = 10)
	public BigDecimal getMontantRemise() {
		return this.montantRemise;
	}

	public void setMontantRemise(BigDecimal montantRemise) {
		this.montantRemise = montantRemise;
	}

	@Column(name = "MONTANT_TVA", precision = 18, scale = 3)
	public BigDecimal getMontantTva() {
		return this.montantTva;
	}

	public void setMontantTva(BigDecimal montantTva) {
		this.montantTva = montantTva;
	}

	@Column(name = "NUM_VENTE", nullable = false, length = 15)
	public String getNumVente() {
		return this.numVente;
	}

	public void setNumVente(String numVente) {
		this.numVente = numVente;
	}

	@Column(name = "NUM_UTILISATEUR", precision = 10, scale = 0)
	public Long getNumUtilisateur() {
		return this.numUtilisateur;
	}

	public void setNumUtilisateur(Long numUtilisateur) {
		this.numUtilisateur = numUtilisateur;
	}

	@Column(name = "TYPEVENTE")
	public Integer getTypevente() {
		return this.typevente;
	}

	public void setTypevente(Integer typevente) {
		this.typevente = typevente;
	}

	@Column(name = "MONTANT_TTC", precision = 10)
	public BigDecimal getMontantTtc() {
		return this.montantTtc;
	}

	public void setMontantTtc(BigDecimal montantTtc) {
		this.montantTtc = montantTtc;
	}

	@Column(name = "MNTREMISEPROMO", precision = 10)
	public BigDecimal getMntremisepromo() {
		return this.mntremisepromo;
	}

	public void setMntremisepromo(BigDecimal mntremisepromo) {
		this.mntremisepromo = mntremisepromo;
	}

	@Column(name = "ERREURCAISSE", precision = 10)
	public BigDecimal getErreurcaisse() {
		return this.erreurcaisse;
	}

	public void setErreurcaisse(BigDecimal erreurcaisse) {
		this.erreurcaisse = erreurcaisse;
	}

	@Column(name = "TAUX_REMISE", precision = 10, scale = 4)
	public BigDecimal getTauxRemise() {
		return this.tauxRemise;
	}

	public void setTauxRemise(BigDecimal tauxRemise) {
		this.tauxRemise = tauxRemise;
	}

	@Column(name = "NUM_CLIENT", precision = 10, scale = 0)
	public Long getNumClient() {
		return this.numClient;
	}

	public void setNumClient(Long numClient) {
		this.numClient = numClient;
	}

	@Column(name = "NUM_CAISSE", precision = 3, scale = 0)
	public Short getNumCaisse() {
		return this.numCaisse;
	}

	public void setNumCaisse(Short numCaisse) {
		this.numCaisse = numCaisse;
	}

	@Column(name = "NUM_VENTE_RETOUR", precision = 10, scale = 0)
	public Long getNumVenteRetour() {
		return this.numVenteRetour;
	}

	public void setNumVenteRetour(Long numVenteRetour) {
		this.numVenteRetour = numVenteRetour;
	}

	@Column(name = "MONTANT_RESTE", precision = 10)
	public BigDecimal getMontantReste() {
		return this.montantReste;
	}

	public void setMontantReste(BigDecimal montantReste) {
		this.montantReste = montantReste;
	}

	@Column(name = "ACOMPTE", precision = 10)
	public BigDecimal getAcompte() {
		return this.acompte;
	}

	public void setAcompte(BigDecimal acompte) {
		this.acompte = acompte;
	}

	@Column(name = "OBSERVATION", length = 50)
	public String getObservation() {
		return this.observation;
	}

	public void setObservation(String observation) {
		this.observation = observation;
	}

	@Column(name = "NUM_JOURNEE", nullable = false, precision = 18, scale = 0)
	public long getNumJournee() {
		return this.numJournee;
	}

	public void setNumJournee(long numJournee) {
		this.numJournee = numJournee;
	}

	@Column(name = "MONTANT_RENDU", precision = 18)
	public BigDecimal getMontantRendu() {
		return this.montantRendu;
	}

	public void setMontantRendu(BigDecimal montantRendu) {
		this.montantRendu = montantRendu;
	}

	@Column(name = "NUM_AVOIR_PROMO", precision = 18, scale = 0)
	public Long getNumAvoirPromo() {
		return this.numAvoirPromo;
	}

	public void setNumAvoirPromo(Long numAvoirPromo) {
		this.numAvoirPromo = numAvoirPromo;
	}

	@Column(name = "NUM_MAGASIN_CLIENT", precision = 10, scale = 0)
	public Long getNumMagasinClient() {
		return this.numMagasinClient;
	}

	public void setNumMagasinClient(Long numMagasinClient) {
		this.numMagasinClient = numMagasinClient;
	}

	@Column(name = "NUM_PROMO_PROVOQUE", precision = 10, scale = 0)
	public Long getNumPromoProvoque() {
		return this.numPromoProvoque;
	}

	public void setNumPromoProvoque(Long numPromoProvoque) {
		this.numPromoProvoque = numPromoProvoque;
	}

	@Column(name = "LIEU_SAISIE", nullable = false, precision = 18, scale = 0)
	public long getLieuSaisie() {
		return this.lieuSaisie;
	}

	public void setLieuSaisie(long lieuSaisie) {
		this.lieuSaisie = lieuSaisie;
	}

	@Column(name = "TYPE_MVT", nullable = false, length = 10)
	public String getTypeMvt() {
		return this.typeMvt;
	}

	public void setTypeMvt(String typeMvt) {
		this.typeMvt = typeMvt;
	}

	@Column(name = "MAJ_STK", nullable = false)
	public int getMajStk() {
		return this.majStk;
	}

	public void setMajStk(int majStk) {
		this.majStk = majStk;
	}

	@Column(name = "SENS_STK", nullable = false)
	public int getSensStk() {
		return this.sensStk;
	}

	public void setSensStk(int sensStk) {
		this.sensStk = sensStk;
	}

	@Column(name = "MAJ_RESA", nullable = false)
	public int getMajResa() {
		return this.majResa;
	}

	public void setMajResa(int majResa) {
		this.majResa = majResa;
	}

	@Column(name = "IMPORT", nullable = false)
	public int getImport_() {
		return this.import_;
	}

	public void setImport_(int import_) {
		this.import_ = import_;
	}

	@Column(name = "DED_RESA", nullable = false)
	public int getDedResa() {
		return this.dedResa;
	}

	public void setDedResa(int dedResa) {
		this.dedResa = dedResa;
	}

	@Column(name = "DED_LIVR", nullable = false)
	public int getDedLivr() {
		return this.dedLivr;
	}

	public void setDedLivr(int dedLivr) {
		this.dedLivr = dedLivr;
	}

	@Column(name = "NUM_MOTIF", precision = 18, scale = 0)
	public Long getNumMotif() {
		return this.numMotif;
	}

	public void setNumMotif(Long numMotif) {
		this.numMotif = numMotif;
	}

	@Column(name = "MONTANT_HT_PAYS", precision = 18)
	public BigDecimal getMontantHtPays() {
		return this.montantHtPays;
	}

	public void setMontantHtPays(BigDecimal montantHtPays) {
		this.montantHtPays = montantHtPays;
	}

	@Column(name = "MONTANT_REMISE_PAYS", precision = 18)
	public BigDecimal getMontantRemisePays() {
		return this.montantRemisePays;
	}

	public void setMontantRemisePays(BigDecimal montantRemisePays) {
		this.montantRemisePays = montantRemisePays;
	}

	@Column(name = "MONTANT_TVA_PAYS", precision = 18)
	public BigDecimal getMontantTvaPays() {
		return this.montantTvaPays;
	}

	public void setMontantTvaPays(BigDecimal montantTvaPays) {
		this.montantTvaPays = montantTvaPays;
	}

	@Column(name = "MONTANT_TTC_PAYS", precision = 18)
	public BigDecimal getMontantTtcPays() {
		return this.montantTtcPays;
	}

	public void setMontantTtcPays(BigDecimal montantTtcPays) {
		this.montantTtcPays = montantTtcPays;
	}

	@Column(name = "MNTREMISEPROMO_PAYS", precision = 18)
	public BigDecimal getMntremisepromoPays() {
		return this.mntremisepromoPays;
	}

	public void setMntremisepromoPays(BigDecimal mntremisepromoPays) {
		this.mntremisepromoPays = mntremisepromoPays;
	}

	@Column(name = "MONTANT_RESTE_PAYS", precision = 18)
	public BigDecimal getMontantRestePays() {
		return this.montantRestePays;
	}

	public void setMontantRestePays(BigDecimal montantRestePays) {
		this.montantRestePays = montantRestePays;
	}

	@Column(name = "MONTANT_RENDU_PAYS", precision = 18)
	public BigDecimal getMontantRenduPays() {
		return this.montantRenduPays;
	}

	public void setMontantRenduPays(BigDecimal montantRenduPays) {
		this.montantRenduPays = montantRenduPays;
	}

	@Column(name = "NUM_DEVISE", precision = 10, scale = 0)
	public Long getNumDevise() {
		return this.numDevise;
	}

	public void setNumDevise(Long numDevise) {
		this.numDevise = numDevise;
	}

	@Column(name = "TAUX_DEVISE", precision = 10, scale = 4)
	public BigDecimal getTauxDevise() {
		return this.tauxDevise;
	}

	public void setTauxDevise(BigDecimal tauxDevise) {
		this.tauxDevise = tauxDevise;
	}

	@Column(name = "UNITE_DEVISE")
	public Integer getUniteDevise() {
		return this.uniteDevise;
	}

	public void setUniteDevise(Integer uniteDevise) {
		this.uniteDevise = uniteDevise;
	}

	@Column(name = "code_remise", length = 10)
	public String getCodeRemise() {
		return this.codeRemise;
	}

	public void setCodeRemise(String codeRemise) {
		this.codeRemise = codeRemise;
	}

	@Column(name = "STATUS_FACTURE", length = 1)
	public Character getStatusFacture() {
		return this.statusFacture;
	}

	public void setStatusFacture(Character statusFacture) {
		this.statusFacture = statusFacture;
	}

	@Column(name = "NUM_FACTURE", length = 20)
	public String getNumFacture() {
		return this.numFacture;
	}

	public void setNumFacture(String numFacture) {
		this.numFacture = numFacture;
	}

	@Column(name = "NUM_JOURNEE_CAISSIER", precision = 18, scale = 0)
	public Long getNumJourneeCaissier() {
		return this.numJourneeCaissier;
	}

	public void setNumJourneeCaissier(Long numJourneeCaissier) {
		this.numJourneeCaissier = numJourneeCaissier;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "DATETIME_CREATION", length = 23)
	public Date getDatetimeCreation() {
		return this.datetimeCreation;
	}

	public void setDatetimeCreation(Date datetimeCreation) {
		this.datetimeCreation = datetimeCreation;
	}

	@Column(name = "CODE_ACTION_PRINCIPALE", length = 20)
	public String getCodeActionPrincipale() {
		return this.codeActionPrincipale;
	}

	public void setCodeActionPrincipale(String codeActionPrincipale) {
		this.codeActionPrincipale = codeActionPrincipale;
	}

	@Column(name = "DROIT_TIMBRE", precision = 18)
	public BigDecimal getDroitTimbre() {
		return this.droitTimbre;
	}

	public void setDroitTimbre(BigDecimal droitTimbre) {
		this.droitTimbre = droitTimbre;
	}

	@Column(name = "CODE_PLV_ENCOURS", length = 20)
	public String getCodePlvEncours() {
		return this.codePlvEncours;
	}

	public void setCodePlvEncours(String codePlvEncours) {
		this.codePlvEncours = codePlvEncours;
	}

	@Column(name = "BASE_REMISE", precision = 10)
	public BigDecimal getBaseRemise() {
		return this.baseRemise;
	}

	public void setBaseRemise(BigDecimal baseRemise) {
		this.baseRemise = baseRemise;
	}

	@Column(name = "TAUX_REMISE_ACCORDE", precision = 10, scale = 4)
	public BigDecimal getTauxRemiseAccorde() {
		return this.tauxRemiseAccorde;
	}

	public void setTauxRemiseAccorde(BigDecimal tauxRemiseAccorde) {
		this.tauxRemiseAccorde = tauxRemiseAccorde;
	}

	@Column(name = "TYPE_TYPE_MVT")
	public String getTypeTypeMvt() {
		return this.typeTypeMvt;
	}

	public void setTypeTypeMvt( String typeTypeMvt) {
		this.typeTypeMvt = typeTypeMvt;
	}

	@Column(name = "CODE_UTILISATEUR_AUTORISE")
	public String getCodeUtilisateurAutorise() {
		return this.codeUtilisateurAutorise;
	}

	public void setCodeUtilisateurAutorise(String codeUtilisateurAutorise) {
		this.codeUtilisateurAutorise = codeUtilisateurAutorise;
	}

	@Column(name = "INDEX_CHAISES")
	public String getIndexChaises() {
		return this.indexChaises;
	}

	public void setIndexChaises(String indexChaises) {
		this.indexChaises = indexChaises;
	}

	@Column(name = "POINTS_FIDELITE")
	public Integer getPointsFidelite() {
		return this.pointsFidelite;
	}

	public void setPointsFidelite(Integer pointsFidelite) {
		this.pointsFidelite = pointsFidelite;
	}

	@Transient
	public int getHour() {
		return this.hour;
	}

	public void setHour(int hour) {
		this.hour = hour;
	}

	@Transient
	public Integer getNmbreTicket() {
		return this.nmbreTicket;
	}

	public void setNmbreTicket(Integer nmbreTicket) {
		this.nmbreTicket = nmbreTicket;
	}
	
	@OneToMany(fetch = FetchType.LAZY ,cascade = CascadeType.ALL,  mappedBy = "stkVenteDirecte")
	public Set<LineVenteDirect> getLineVenteDirects() {
		return lineVenteDirects;
	}

	public void setLineVenteDirects(Set<LineVenteDirect> lineVenteDirects) {
		this.lineVenteDirects = lineVenteDirects;
	}
}
