package ma.sofisoft.cam2020ws.entity;
// Generated 15 nov. 2019 10:03:37 by Hibernate Tools 4.3.5.Final

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * StkVenteDirecteId generated by hbm2java
 */
@Embeddable
public class StkVenteDirecteId implements java.io.Serializable {

	private int numMvt;
	private long numMagasin;

	public StkVenteDirecteId() {
	}

	public StkVenteDirecteId(int numMvt, long numMagasin) {
		this.numMvt = numMvt;
		this.numMagasin = numMagasin;
	}

	@Column(name = "NUM_MVT", nullable = false)
	public int getNumMvt() {
		return this.numMvt;
	}

	public void setNumMvt(int numMvt) {
		this.numMvt = numMvt;
	}

	@Column(name = "NUM_MAGASIN", nullable = false, precision = 10, scale = 0)
	public long getNumMagasin() {
		return this.numMagasin;
	}

	public void setNumMagasin(long numMagasin) {
		this.numMagasin = numMagasin;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof StkVenteDirecteId))
			return false;
		StkVenteDirecteId castOther = (StkVenteDirecteId) other;

		return (this.getNumMvt() == castOther.getNumMvt()) && (this.getNumMagasin() == castOther.getNumMagasin());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getNumMvt();
		result = 37 * result + (int) this.getNumMagasin();
		return result;
	}

}
