package ma.sofisoft.cam2020ws.entity;
// Generated 15 nov. 2019 10:03:37 by Hibernate Tools 4.3.5.Final

import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.UniqueConstraint;

/**
 * VendeurMag generated by hbm2java
 */
@Entity
@Table(name = "VENDEUR_MAG", uniqueConstraints = @UniqueConstraint(columnNames = "MOT_PASSE"))
public class VendeurMag implements java.io.Serializable {

	private long numVendeur;
	private Integer numSociete;
	private String codeVendeur;
	private String nom;
	private String prenom;
	private String adresse;
	private Integer appelation;
	private Date dateNaissance;
	private Date dateDebut;
	private Date dateFin;
	private String observation;
	private Integer bloque;
	private BigDecimal commission;
	private Integer typeCom;
	private long numMagasin;
	private String motPasse;
	private Set<StkVenteDirecte> stkVenteDirectes = new HashSet(0);

	public VendeurMag() {
	}

	public VendeurMag(long numVendeur, String codeVendeur, long numMagasin) {
		this.numVendeur = numVendeur;
		this.codeVendeur = codeVendeur;
		this.numMagasin = numMagasin;
	}

	public VendeurMag(long numVendeur, Integer numSociete, String codeVendeur, String nom, String prenom,
			String adresse, Integer appelation, Date dateNaissance, Date dateDebut, Date dateFin, String observation,
			Integer bloque, BigDecimal commission, Integer typeCom, long numMagasin, String motPasse,
			Set stkVenteDirectes) {
		this.numVendeur = numVendeur;
		this.numSociete = numSociete;
		this.codeVendeur = codeVendeur;
		this.nom = nom;
		this.prenom = prenom;
		this.adresse = adresse;
		this.appelation = appelation;
		this.dateNaissance = dateNaissance;
		this.dateDebut = dateDebut;
		this.dateFin = dateFin;
		this.observation = observation;
		this.bloque = bloque;
		this.commission = commission;
		this.typeCom = typeCom;
		this.numMagasin = numMagasin;
		this.motPasse = motPasse;
		this.stkVenteDirectes = stkVenteDirectes;
	}

	@Id

	@Column(name = "NUM_VENDEUR", unique = true, nullable = false, precision = 10, scale = 0)
	public long getNumVendeur() {
		return this.numVendeur;
	}

	public void setNumVendeur(long numVendeur) {
		this.numVendeur = numVendeur;
	}

	@Column(name = "NUM_SOCIETE")
	public Integer getNumSociete() {
		return this.numSociete;
	}

	public void setNumSociete(Integer numSociete) {
		this.numSociete = numSociete;
	}

	@Column(name = "CODE_VENDEUR", nullable = false, length = 10)
	public String getCodeVendeur() {
		return this.codeVendeur;
	}

	public void setCodeVendeur(String codeVendeur) {
		this.codeVendeur = codeVendeur;
	}

	@Column(name = "NOM", length = 30)
	public String getNom() {
		return this.nom;
	}

	public void setNom(String nom) {
		this.nom = nom;
	}

	@Column(name = "PRENOM", length = 30)
	public String getPrenom() {
		return this.prenom;
	}

	public void setPrenom(String prenom) {
		this.prenom = prenom;
	}

	@Column(name = "ADRESSE", length = 50)
	public String getAdresse() {
		return this.adresse;
	}

	public void setAdresse(String adresse) {
		this.adresse = adresse;
	}

	@Column(name = "APPELATION")
	public Integer getAppelation() {
		return this.appelation;
	}

	public void setAppelation(Integer appelation) {
		this.appelation = appelation;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "DATE_NAISSANCE", length = 23)
	public Date getDateNaissance() {
		return this.dateNaissance;
	}

	public void setDateNaissance(Date dateNaissance) {
		this.dateNaissance = dateNaissance;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "DATE_DEBUT", length = 23)
	public Date getDateDebut() {
		return this.dateDebut;
	}

	public void setDateDebut(Date dateDebut) {
		this.dateDebut = dateDebut;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "DATE_FIN", length = 23)
	public Date getDateFin() {
		return this.dateFin;
	}

	public void setDateFin(Date dateFin) {
		this.dateFin = dateFin;
	}

	@Column(name = "OBSERVATION", length = 120)
	public String getObservation() {
		return this.observation;
	}

	public void setObservation(String observation) {
		this.observation = observation;
	}

	@Column(name = "BLOQUE")
	public Integer getBloque() {
		return this.bloque;
	}

	public void setBloque(Integer bloque) {
		this.bloque = bloque;
	}

	@Column(name = "COMMISSION", precision = 4)
	public BigDecimal getCommission() {
		return this.commission;
	}

	public void setCommission(BigDecimal commission) {
		this.commission = commission;
	}

	@Column(name = "TYPE_COM")
	public Integer getTypeCom() {
		return this.typeCom;
	}

	public void setTypeCom(Integer typeCom) {
		this.typeCom = typeCom;
	}

	@Column(name = "NUM_MAGASIN", nullable = false, precision = 10, scale = 0)
	public long getNumMagasin() {
		return this.numMagasin;
	}

	public void setNumMagasin(long numMagasin) {
		this.numMagasin = numMagasin;
	}

	@Column(name = "MOT_PASSE", unique = true, length = 15)
	public String getMotPasse() {
		return this.motPasse;
	}

	public void setMotPasse(String motPasse) {
		this.motPasse = motPasse;
	}

	/*@OneToMany(fetch = FetchType.LAZY, mappedBy = "vendeurMag")
	public Set<StkVenteDirecte> getStkVenteDirectes() {
		return this.stkVenteDirectes;
	}

	public void setStkVenteDirectes(Set<StkVenteDirecte> stkVenteDirectes) {
		this.stkVenteDirectes = stkVenteDirectes;
	}*/

}
